/* BUZZ BOARD big-screen host — read-only public spectator. */
"use strict";
const $=(id)=>document.getElementById(id); let ST=null,lastStage="",wake=null,started=false;
const esc=(s)=>String(s??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=(n)=>(n<0?"−$"+Math.abs(n).toLocaleString():"$"+Number(n||0).toLocaleString());
const player=(pid)=>ST?.players?.find((p)=>p.pid===pid)||null; const nameOf=(pid)=>player(pid)?.name||"PLAYER";
const SFX=(()=>{let c=null;const tone=(f,t="sine",d=.1,v=.07,x=0,g=0)=>{if(!started)return;try{if(!c)c=new(window.AudioContext||window.webkitAudioContext)();if(c.state==="suspended")c.resume();const o=c.createOscillator(),a=c.createGain(),at=c.currentTime+x;o.type=t;o.frequency.setValueAtTime(f,at);if(g)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+g),at+d);a.gain.setValueAtTime(.0001,at);a.gain.exponentialRampToValueAtTime(v,at+.015);a.gain.exponentialRampToValueAtTime(.0001,at+d);o.connect(a);a.connect(c.destination);o.start(at);o.stop(at+d+.03)}catch(e){}};return{unlock(){started=true;try{if(!c)c=new(window.AudioContext||window.webkitAudioContext)();c.resume()}catch(e){}},pick(){tone(520,"square",.06,.05);tone(760,"square",.05,.035,.05)},buzz(){tone(95,"sawtooth",.24,.13,0,360)},right(){[523,659,784,1047].forEach((f,i)=>tone(f,"sine",.25,.09,i*.08))},wrong(){tone(145,"sawtooth",.28,.09)},hot(){[196,294,392,587].forEach((f,i)=>tone(f,"triangle",.4,.1,i*.13))},power(){tone(80,"sawtooth",.8,.13,0,600);tone(880,"square",.35,.05,.35)},final(){[220,277,330,440].forEach((f,i)=>tone(f,"triangle",.6,.075,i*.18))}}})();

const joinUrl=new URL("." + (window.AvranaIntegration?.integrated ? "?avrana=1" : ""),location.href).href;$("tv-url").textContent=joinUrl.replace(/^https?:\/\//,"");try{renderQR($("tv-qr"),joinUrl)}catch(e){$("tv-qr").textContent="open the address below"}
async function holdWake(){try{wake=await navigator.wakeLock?.request("screen")}catch(e){}}
$("tv-start").onclick=()=>{SFX.unlock();holdWake();$("tv-curtain").hidden=true;};
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&started)holdWake()});

function roster(st){const host=$("tv-roster");host.textContent="";const g=st.game;const rows=g?.roster||st.players.map((p)=>({pid:p.pid,score:0}));for(const r of rows){const p=st.players.find((x)=>x.pid===r.pid);if(!p)continue;const activeControl=r.selector&&["board","hot_wager","hot_answer"].includes(g?.stage);const el=document.createElement("div");el.className="tv-pl"+(activeControl?" bb-control":"")+(r.buzzed?" win":"");const av=document.createElement("span");av.className="tv-av";Hub.fillAvatar(av,p);const nm=document.createElement("span");nm.className="tv-pl-name";nm.textContent=p.name+(r.selector&&g?.stage==="board"?" · PICK":"");const score=document.createElement("span");score.className="tv-pl-meta bb-score"+(r.score<0?" neg":"");score.textContent=g?money(r.score):(p.ready?"READY":"…");el.append(av,nm,score);host.appendChild(el)}}
function lobby(st){const n=st.players.filter((p)=>!p.bot).length;$("tv-stage").innerHTML='<div class="tv-kicker">'+esc(window.brandPresents?window.brandPresents():"LAN GAMES PRESENTS")+'</div><div class="bb-splash">BUZZ<br>BOARD</div><div class="tv-sub">'+(n?esc(n+" contestant"+(n===1?"":"s")+" in the studio · ready up on a phone"):"Scan the code. Grab a buzzer. Bring your nerve.")+'</div>'}
function board(g){const root=document.createElement("div");root.className="bb-board";root.style.setProperty("--cats",g.board.length);root.style.setProperty("--rows",g.board[0]?.cells?.length||3);for(const cat of g.board){const col=document.createElement("div");col.className="bb-col";const h=document.createElement("div");h.className="bb-cat";h.textContent=cat.icon+" "+cat.title;col.appendChild(h);for(const c of cat.cells){const v=document.createElement("div");v.className="bb-cell"+(c.used?" used":"");v.textContent=c.used?"":money(c.value);col.appendChild(v)}root.appendChild(col)}const stage=$("tv-stage");stage.textContent="";stage.appendChild(root)}
function clueCard(kicker,question,callout="",cls=""){const stage=$("tv-stage");stage.innerHTML='<div class="bb-clue '+cls+'"><div class="bb-kicker">'+esc(kicker)+'</div><div class="bb-question">'+esc(question)+'</div>'+(callout?'<div class="bb-callout '+(callout.includes("OPEN")?"open":"")+'">'+esc(callout)+'</div>':"")+'</div>'}
function renderStage(st){const g=st.game,stage=g?.stage||st.phase;if(stage==="lobby"||stage==="countdown"){lobby(st);return}if(stage==="board"){board(g);return}const c=g.current;if(stage==="hot_wager"){clueCard("THE BOARD IS ON FIRE","HOT CLUE",nameOf(g.roster.find((r)=>r.selector)?.pid)+" MAKES A SECRET WAGER","hot");return}if(["clue","buzz","answer","reveal","hot_answer"].includes(stage)){const kick=(c?.hot?"🔥 HOT CLUE · ":"")+(c?.category||"")+" · "+money(c?.value||0);let call="";if(stage==="clue")call="BUZZERS LOCKED";if(stage==="buzz")call="BUZZERS OPEN";if(stage==="answer")call=nameOf(g.roster.find((r)=>r.buzzed)?.pid)+" HAS THE FLOOR";if(stage==="hot_answer")call=nameOf(g.roster.find((r)=>r.selector)?.pid)+" GOES SOLO";if(stage==="reveal")call="CORRECT: "+(c?.answer||"");clueCard(kick,c?.clue||"",call,c?.hot?"hot":"");if(stage==="reveal"&&g.reveal?.attempts?.length){const a=document.createElement("div");a.className="bb-attempts";for(const x of g.reveal.attempts){const e=document.createElement("span");e.className="bb-attempt";e.textContent=nameOf(x.pid)+" · "+money(x.delta);a.appendChild(e)}$("tv-stage").querySelector(".bb-clue").appendChild(a)}return}if(stage==="final_wager"){clueCard("LAST CALL CATEGORY",g.final.category,"SECRET WAGERS ARE OPEN","hot");return}if(stage==="final_answer"){clueCard("LAST CALL · "+g.final.category,g.final.clue,"EVERY ANSWER IS SECRET","hot");return}if(stage==="final_reveal"||st.phase==="game_end"){const rows=g.final.rows||[];clueCard("LAST CALL ANSWER",g.final.answer||"",st.phase==="game_end"?"FINAL SCORES":"WAGERS REVEALED","hot");const box=document.createElement("div");box.className="bb-final-rows";for(const r of rows){const e=document.createElement("div");e.className="bb-final-row "+(r.correct?"ok":"bad");e.innerHTML='<b>'+esc(nameOf(r.pid))+'</b><span>'+esc(r.choice)+' · '+(r.correct?"+":"−")+money(r.wager).replace(/[−]/g,"")+'</span><b>'+esc(money(r.score))+'</b>';box.appendChild(e)}$("tv-stage").querySelector(".bb-clue").appendChild(box);if(st.phase==="game_end"&&g.result?.length){const top=g.result[0].score,w=g.result.filter((r)=>r.score===top);if(w.length)Hub.confettiBurst(280)}return}}
function flash(text,ms=1900){const f=$("tv-flash");f.textContent=text;f.hidden=false;setTimeout(()=>f.hidden=true,ms)}
function render(st){if(!st)return;ST=st;const humans=st.players.filter((p)=>!p.bot).length;$("tv-online").textContent=humans?"● "+humans+" playing":"no players yet";$("tv-online").classList.toggle("on",humans>0);renderStage(st);roster(st);lastStage=st.game?.stage||st.phase}
Hub.connect("/games/buzzboard/ws",{onState:render,onFx:(fx)=>{if(fx.kind==="clue")SFX.pick();if(fx.kind==="buzz")SFX.buzz();if(fx.kind==="wrong")SFX.wrong();if(fx.kind==="reveal"&&fx.winner)SFX.right();if(fx.kind==="hot_clue"){flash("🔥 HOT CLUE");SFX.hot()}if(fx.kind==="power_surge"){flash("⚡ POWER SURGE\nVALUES DOUBLED",2600);SFX.power()}if(fx.kind==="last_call"){flash("LAST CALL",2200);SFX.final()}}},{watch:true});
