#!/usr/bin/env node
// Build games/bluff/web/art.js: BLUFF's game art (roles, coins, actions, crown, log markers)
// from the vendored, unmodified Kenney Board Game Icons originals in games/bluff/art/kenney/
// (CC0; docs/ASSETS.md).
//
//   node ops/build_bluff_art.mjs            write art.js
//   node ops/build_bluff_art.mjs --check    exit 1 if art.js is stale (ops/check_static.sh)
//
// Dependency-free. Each icon becomes path data drawn as an inline <svg> with fill=currentColor,
// so the card, bar or log decides its colour.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'games', 'bluff', 'art', 'kenney');
const out = path.join(root, 'games', 'bluff', 'web', 'art.js');

const paths = Object.fromEntries(readdirSync(src).filter((f) => f.endsWith('.svg')).sort().map((f) => {
  const svg = readFileSync(path.join(src, f), 'utf8');
  const d = [...svg.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!d.length || /transform=|<use|fill-rule/.test(svg)) throw new Error(`${f}: unexpected structure`);
  return [f.replace(/\.svg$/, ''), d];
}));

const source = `/* GENERATED by ops/build_bluff_art.mjs from games/bluff/art/kenney/ (Kenney Board Game
   Icons 1.1, CC0; docs/ASSETS.md). Do not edit; rebuild. BLUFF's own game art: every icon is
   one-colour and takes the colour of where it is drawn. */
"use strict";

window.BluffArt = (() => {
  const PATHS = ${JSON.stringify(paths)};
  const NS = "http://www.w3.org/2000/svg";
  // Decorative unless a label is given (then it is an image with that name).
  return function art(name, label) {
    const svg = document.createElementNS(NS, "svg");
    svg.setAttribute("viewBox", "-32 -32 64 64");
    svg.setAttribute("fill", "currentColor");
    svg.setAttribute("class", "bart");
    svg.setAttribute("focusable", "false");
    if (label) { svg.setAttribute("role", "img"); svg.setAttribute("aria-label", label); }
    else svg.setAttribute("aria-hidden", "true");
    for (const d of PATHS[name] || []) {
      const p = document.createElementNS(NS, "path");
      p.setAttribute("d", d);
      svg.appendChild(p);
    }
    return svg;
  };
})();
`;

if (process.argv.includes('--check')) {
  let current = null;
  try { current = readFileSync(out, 'utf8'); } catch { /* missing = stale */ }
  if (current !== source) { console.error('games/bluff/web/art.js is stale: run node ops/build_bluff_art.mjs'); process.exit(1); }
  console.log('bluff art is current');
} else {
  writeFileSync(out, source);
  console.log(`bluff art: ${Object.keys(paths).length} icons, ${source.length} bytes`);
}
